version: '3.1'
services:
  API:
    image: 'blog-api-docker.jar'
    ports:
      - "9090:9090"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/e-shop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=web
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=web
      - POSTGRES_DB=e-shop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml --web.enable-admin-api 
                                                         --web.listen-address=192.168.0.5:8080"

#    ports:
#      - 9090:9090


#  grafana:
#    image: grafana/grafana-oss:8.5.2
#    network_mode: host
#    container_name: grafana
#    restart: unless-stopped
#    user: root
#    ports:
#      - 3000:3000
#    links:
#      - prometheus:prometheus
#    volumes:
#      - ./data/grafana:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_USER_ALLOW_SIGN_UP=false
#      - GF_SERVER_DOMAIN=localhost
#      - GF_LOG_MODE=console file
#      - GF_LOG_FILTERS=alterting.notifier.slack:debug alertmanager:debug ngalert:debug
#
